### ISSUE TITLE
Surprised by Elixir Results 

### ISSUE THREAD

**Issue by trans** [losvedir/transit-lang-cmp#3]
I’m really surprised by the Elixir results. I don’t expect them to be exceptional compared to the likes of Rust and C, but I’d expect them be at better than this. I’m curious where the major bottleneck is.

Side note, Crystal would a good target for this project too. I suspect Go like performance, but with code that is easier to write (and read) then any of the other implementations.

**Comment by losvedir** [comment]
Aha! Just pushed up [a commit](https://github.com/losvedir/transit-lang-cmp/commit/6c6c999e5d50802118a7b0adffc8a367cdf7547f) with updated benchmarks. I was stupidly failing to run it with `MIX_ENV=prod`. Elixir is still the slowest of all of them, but now much more respectable.

Since the title is about Elixir's results, I'm going to close the issue now. I don't think these new results are "surprisingly" bad anymore, though feel free to re-open if you still think something is amiss.
